### ISSUE TITLE
How to on mongodb or have local db for development purpose

### ISSUE THREAD

**Issue by pieterdeschepper** [CodingTrain/GUMP500#6]
A small write-up on how to set up your own mongodb instance on mongodb.net or a way to test it localy would be beneficial for collaboration and test code without connecting to the live database.
Right now it's not possible to test the code without the username / password or to set up an own mongodb somewhere.

**Comment by shiffman** [comment]
Yes, I was thinking about this too!! If anyone has ideas on how to best approach would love to hear.

**Comment by pieterdeschepper** [comment]
An alternative would be to use [firebase cloud firestore](https://googleapis.dev/nodejs/firestore/latest/). It is free for limited use (enough for this type project), and easy for anyone to set up to use locally, it would just need another endpoint in the .env file. 
I can take a look to migrate this from mongodb to firebase if you believe this would be a good solution?

**Comment by shiffman** [comment]
I was hoping to learn mongodb with this project (i've used firebase before), I would imagine there's an equivalent local solution for testing/developing with mongodb?

**Comment by pieterdeschepper** [comment]
Fair enough. I'll see if I can come up with a good mongodb solution

**Comment by pieterdeschepper** [comment]
basic implementation [here](https://github.com/CodingTrain/GUMP500/pull/7)
